<<<<<<< HEAD
spring.application.name=aqi-backend
server.port=8080

# === OpenWeatherMap API ===
owm.api.key=3d543d0636a4950860b22999f5301793

# === Supabase PostgreSQL (Session Pooler - IPv4) ===
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ileoodctldnhridhabuj
spring.datasource.password=p$xP-qY-KKP6p@T
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
=======

spring.application.name=aqi-backend
server.port=8080

# === OpenWeatherMap API (weather + air pollution) ===
# Get free key at: https://openweathermap.org/api
owm.api.key=3d543d0636a4950860b22999f5301793
>>>>>>> origin/main
